### ISSUE TITLE
logo enhancement

### ISSUE THREAD

**Issue by ScratchDiogoh** [Scratch3ds/Scratch3ds#1]
in the logo designed by @HeyHeyPizza111 is bitmap, to improve it should be in vectors for better quality
Link Image:
https://github.com/orgs/Scratch3ds/teams/graphics-designers/discussions/1

**Comment by HeyHeyPizza111** [comment]
boi it too late it's already inside the folder of assets

**Comment by Gadzooks2** [comment]
I can change the repository contents, so if @Scratch3ds/graphics-designers change it to vector, I'll re-upload it.

**Comment by Gadzooks2** [comment]
Oh wait, it's 48px by 48px, which is how it'll stay.
