### ISSUE TITLE
Make main.c read out about.txt rather than being hardcoded in

### ISSUE THREAD

**Issue by TolerableDruid6** [Scratch3ds/Scratch3ds#7]
Right now, the contents of about.txt are copied and hardcoded into main.c:

printf("About Scratch3ds\n");
	printf("________________________\n");
	printf("Scratch3ds Version %i.%i.%i by Gadzooks2\n", version_major, version_minor, version_patch);
	printf("Based on Scratch 2.0 by MIT and the Lifelong Kind-\n-ergarten Media Group\n");
	printf("Programming: Gadzooks2 (@Shaymin524 on Scratch)\n");
	printf("Graphics Design: HeyHeyPizza111\n");
printf("UI Design & Concept: TolerableDruid6 (@dude341 on Scratch)\n");

Rather than doing this, it should actually read from about.txt and print its contents. This way, the text can be easily updated, and it also makes the code cleaner because it avoids repetition.

**Comment by Gadzooks2** [comment]
I was going to do that, but I'f have to somehow add fstream to the repo, and I don't know how to do that.

I'll look in to it.

**Comment by TolerableDruid6** [comment]
Alright, sounds good.

**Comment by ghost** [comment]
I think i fixed it but i'm not sure if it works

**Comment by ghost** [comment]
I tested it and i did it
